Add library code
Satont/grammy-file-storage pull request #1
Opened 2021-10-15 13:25 UTC by Satont

/cc @KnorpelSenf

Not sure i'm implement deno api's in correct way. You can correct me.

2021-10-15 13:35 UTC, KnorpelSenf requested changes

2021-10-15 13:35 UTC, KnorpelSenf commented on src/deps.deno.ts
> +import { exists, existsSync, ensureDirSync } from 'https://deno.land/std@0.77.0/fs/mod.ts'
Please use the newest version of `std`

2021-10-15 13:35 UTC, KnorpelSenf commented on src/mod.ts
> +  }
I think we can reduce the number of files in the directory drastically by using the last two characters of the session key as sub-folders, and doing that twice. This is roughly how git does it. Having tens of thousands of files in the same directory can cause performance problems, but having tens of thousands of users is very common.

2021-10-15 13:35 UTC, KnorpelSenf commented on tsconfig.json
> +    "target": "ES2020",
I think this requires a higher version of Node than grammY ensures.

2021-10-15 13:42 UTC, Satont commented on tsconfig.json
> +    "target": "ES2020",
Is es5 ok?

2021-10-15 13:43 UTC, Satont commented on src/mod.ts
> +  }
> This is roughly how git does it. Having tens of thousands of files in the same directory can cause performance problems,

Make sense.

So, can you give example how it should be?

2021-10-15 13:45 UTC, Satont commented on tsconfig.json
> +    "target": "ES2020",
Didn't found any information on required node version in grammy docs, btw.

2021-10-15 14:34 UTC, KnorpelSenf commented on tsconfig.json
> +    "target": "ES2020",
The package.json file defines the engine field and https://node.green tells you which syntax is supported.

Otherwise, grammY defines ES2019 as target.

2021-10-20 07:09 UTC, KnorpelSenf requested changes
Generally looks good! Just a few minor comments:

2021-10-20 07:09 UTC, KnorpelSenf commented on src/deps.node.ts
> +    if (!existsSync(path)) {
This check is redundant. Passing `recursive: true` already permits the path to exist, much like `mkdir -p`. Confer the Node docs about this.

2021-10-20 07:09 UTC, KnorpelSenf commented on src/mod.ts
> +    const folderPath = fullPath.replace(`${key}.json`, '')
I mean I think this works … but proper file path handling is usually not done via string replacement. It's unlikely to happen, but in theory a file path `/home/me/1234.json/bot/session/` cannot be used to store session data.

2021-10-20 11:52 UTC, Satont commented on src/mod.ts
> +    const folderPath = fullPath.replace(`${key}.json`, '')
changed to substring instead of replace

2021-10-20 19:20 UTC, merged